exp_id: "OrganMNIST_NoMemory"

device: "cuda:0"

results_dir: "./results"

ContinualLearning:
  Replay:
    use_replay: False
    memory_strategy: "Uniform"
    capacity: 1000
    lambda_replay: 0.0
  EWC:
    use_ewc: False
    lambda_ewc: 0.0e3

Dataset:
  dataset_type: OrganMNIST
  Lite: True
  num_classes: 11

Model:
  model_type: "OrganCNN"

Training:
  epochs: 20
  lr: 1.0e-3
  weight_decay: 1.0e-5
  batch_size: 64
  n_repetitions: 10

Optuna:
  n_trials: 30